services:
  - type: web
    name: rifa-online
    runtime: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
